const mongoose = require("mongoose");

const MT = mongoose.model(
  "MT",
  new mongoose.Schema({
    bankName: {
      type: String,
      required:true
    },
    loanName: {
      type: String,
      required:true
    },
    trancheName: {
      type: String,
      required:true
    },
    shortCode: {
      type: String,
    },
    shortCodeLenderWise:{
      type:String
    },
    actualNo:{
      type:String
    },
    moratoriumStatusPhase1:{
      type:String
    },
    moratoriumStatusPhase2:{
      type:String
    },
    amountSanctioned:{
      type:Number,
      required:true,
    },
    sanctionDate:{
      type:Date,
      required:true
    },
    disbursementDate:{
      type:Date,
      required:true
    },
    amountDisbursed:{
      type:Number,
      required:true
    },
    processingFee:{
      type:Number,
      default:0
    },
    fdr:{
      type:Number,
      default:0
    },
    margin:{
      type:Number,
      default:0
    },
    noOfMonthsMoratorium:{
      type:Number,
      default:0
    },
    roi:{
      type:Number,
      required:true
    },
    tenure:{
      type:Number,
      required:true
    },
    repaymentSchedule:{
      type:String,
      required:true
    },
    emiStartDate:{
      type:Date,
      required:true
    },
    otherExp:{
      type:Number,
      default:0
    },
    intOnFdr:{
      type:Number,
      default:0
    },
    fundRaisedDuringFY:{
      type:Number,
      default:0
    },
    baseRate:{
      type:String
    },
    roiGross:{
      type:Number,
      default:0
    },
    roiNet:{
      type:Number,
      default:0
    },
    anyChangeInInterestDuringYear:{
      type:String
    },
    dateOfChangeOfInterest:{
      type:Date
    },
    newRate:{
      type:Number,
      default:0
    },
    currentRoi:{
      type:Number,
      default:0
    },
    roiType:{
      type:String
    },
    pg:{
      type:String
    },
    rating:{
      type:String
    },
    availedAmount:{
      type:Number,
      default:0
    },
    termsOfTextRepayment1_P:{
      type:String
    },
    termsOfTextRepayment2_P:{
      type:String
    },
    termsOfTextRepayment1_I:{
      type:String
    },
    termsOfTextRepayment2_I:{
      type:String
    },
    typeOfLender1:{
      type:String
    },
    typeOfLender2:{
      type:String
    },
    natureOfInstrument1:{
      type:String
    },
    natureOfInstrument2:{
      type:String
    },
    natureOfInstrument3:{
      type:String
    },
    typeOfLender3:{
      type:String
    },
    typeOfFacility:{
      type:String
    },
    paymentFrequency:{
      type:String
    },
    originalMaturityOfLoan:{
      type:String
    },
    interestRate:{
      type:Number,
      default:0
    },
    sanctionLetter:{
      type:Date
    },
    maturityDate:{
      type:Date
    },
    thDate:{
      type:Date
    },
    compounding:{
      type:String
    },
    changeEffectiveDate:{
      type:Date
    },
    legalFee:{
      type:Number,
      default:0
    },
    documentationCharges:{
      type:Number,
      default:0
    },
    stampDuty:{
      type:Number,
      default:0
    },
    trusteeFee:{
      type:Number,
      default:0
    },
    arrangerFee:{
      type:Number,
      default:0
    },
    nsdl:{
      type:Number,
      default:0
    },
    linkinktimeRta:{
      type:Number,
      default:0
    },
    ratingFee:{
      type:Number,
      default:0
    },
    listing:{
      type:Number,
      default:0
    },
    debentureStamping:{
      type:Number,
      default:0
    },
    otherFee:{
      type:Number,
      default:0
    },
    stempDown:{
      type:String
    },
    step:{
      type:String
    },
    applicableTaxes:{
      type:Number,
      default:0
    },
    flag:{
      type:String,
      required:true
    }
  }, {
    timestamps: true
  })
);

module.exports = MT;